// relative styles
import '@mantine/carousel/styles.css';
import '@mantine/core/styles.css';
import './globals.css'
// relative imports
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { MantineProvider } from '@mantine/core'
import { AppFooter } from '@/components/app-footer';
import { AppHeader } from '@/components/app-header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider>
          <AppHeader />
          {children}
          <AppFooter />
        </MantineProvider>
      </body>
    </html>
  )
}
